### ISSUE TITLE
Regex on script src

### ISSUE THREAD

**Issue by julegatti** [quex46/gulp-rev-qs#1]
Hey, I'd like to try your plugin, however I guess it relies on the script src file to calculate the hash, am I right?

in my case I'm working with Django framework, and my scripts src looks like: "{{ STATIC_URL }}js/script.js"

So, is there any regex option to parse and tell this plugin which is actually the asset path?

**Comment by quex46** [comment]
Hi.
Yes, you are right. Hashes are calculated depends on contents of src|href|url attributes.
I've just added `resolver` option to support this case. Now you can do
```
rev({
  resolver: function (assetPath) {
    return assetPath.replace('{{STATIC_PATH}}', '../filepath/to/assets');
  }
});
```
But be sure you are not using spaces inside your src|href|url attribs (src="{{ STATIC_PATH }}..." will not work).

**Comment by julegatti** [comment]
Your're great man.

Gulp just throws me an error with the "=>" operator, is that part of javascript?

```
/home/dione/tmp/uptoeleven-lesscss/node_modules/gulp-rev-qs/index.js:27
  return map((file, cb) => {
                        ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dione/tmp/uptoeleven-lesscss/gulpfile.js:4:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by quex46** [comment]
It happens because the plugin use ES6 features (lambda functions in this case). You probably using old version of node. You can do:
run node with --harmony --harmony_arrow_functions flags
or
update your node version
or
remove all ES6 features from the plugin (pull request are welcome)

**Comment by julegatti** [comment]
Interesting, didn't know about lambda functions, I'll take a look at them. I'll update my node version.

**Comment by quex46** [comment]
ES6 has a lot of cool features, lambdas is just one of them. Take a look :)
