### ISSUE TITLE
Require babel

### ISSUE THREAD

**Issue by ghost** [quex46/gulp-rev-qs#3]
Would it be a good idea to require babeljs inside your plugin in order to make your es6 code compatible?
https://babeljs.io/

I have managed to update my Node, but when I share your plugin they have issues.

**Comment by julegatti** [comment]
es6-shim? https://github.com/paulmillr/es6-shim

**Comment by quex46** [comment]
I've just added legacy js support by removing lambda functions (this is only es6 feature used in this plugin).
Including babeljs creates too much overhead for the small plugin imo.
